### ISSUE TITLE
MVPレビュー

### ISSUE THREAD

**Issue by Tsuchiya2** [soikawachihiro41/osimemo#19]
MVPリリースお疲れ様でした、下記の視点をもとにレビューいたします。

1. READMEから課題解決する実装がされているか&動いている
2. 静的コードチェックが入っている
3. 就活において十分な技術力を示せる機能を実装しているか
4. UIでユーザーが迷わないような導線を作れているか・ユーザーが使いたくなるようなサービス設計ができているか

## READMEから課題解決する実装がされているか&動いている
LGTMです。

## 静的コードチェックが入っている
・Rubocopのリントに引っ掛かりそうなコード（行数が多いetc）が散見されたので修正しましょう。（メソッドとして切り出す・モデルにロジックを寄せるなど）

## 就活において十分な技術力を示せる機能を実装しているか
・サービスを触った感じだと、十分な技術力を示せていないと感じました。（特にページの重さから）
・機能面としてはLINE通知などを実装できていて良さそうですが、ページの表示&操作が画像の重さ？からスムーズではないため、その辺りを重点的に修正&対応しましょう。

## UIでユーザーが迷わないような導線を作れているか・ユーザーが使いたくなるようなサービス設計ができているか
・ページが重くユーザー体験があまり良くなかったです。以下の機能を使って、投稿画像を小さく（ファイルの容量とリサイズ実行）するようにしましょう。
```
◯画像加工・合成
概要：アップロードされた画像のサイズを揃えることで、表示を統一化し、文字を合成することでOGPをより分かりやすくすることができます。これにより、ユーザビリティを向上させることができます。
使用技術・ライブラリ：
- ImageMagick
  - https://imagemagick.org/index.php
  - ImageMagick（イメージマジック）は画像を操作・加工出来るソフトウェア（ツール）です。
- RMagick
  - https://github.com/rmagick/rmagick
  - *RubyからImageMagickを利用できるようにするためのラッパーライブラリがRMagickです。このライブラリを利用することで、Rubyのコードから簡単にImageMagickを操作することができます。CarrierWaveとセットで使われることも多いです。
- MiniMagick
  - https://github.com/minimagick/minimagick
  - RMagickは、大量のメモリを消費するため、省メモリ設計で作られたライブラリであるMiniMagickが代替として利用されることがあります。ただし、MiniMagickは機能が制限されるため、画像加工などの用途によっては、使用できる機能が制限されることがあります。こちらもCarrierWaveとセットで使われることが多いです。
- Cloudinary
  - https://cloudinary.com/
  - https://cloudinary.com/products/programmable_media
  - Cloudinaryは、画像や動画、その他のデジタルアセットを管理、変換・最適化、そして配信まですべてできるサービスです。画像加工のAPIも非常に強力であり、独自の様々な加工を行うことができます。
```
・独自ドメインにしましょう。

上記のレビューをタスクに落とし込み、issueに書きましたら、こちらのissueはcloseしていただいて大丈夫です。
また書き出したissueをもとに本リリースまでのスケジュールを教えていただけますでしょうか？
よろしくお願いいたします。

**Comment by s-chihiro0108** [comment]
レビューいただきありがとうござます。

>2.静的コードチェックが入っている

 Rubocopを使用してMVPリリースをしているのですが引っかかりそうなコードとは、どのようなコードでしょうか。実際にひかかっていないため、修正できません。より詳細な情報提供をお願いします。

>4.UIでユーザーが迷わないような導線を作れているか・ユーザーが使いたくなるようなサービス設計ができているか

すでにMiniMagickを使用して画像のリサイズをしているのですが、さらにファイル容量の調整をおこなうということでよろしいでしょうか。

独自ドメイン承知いたしました。

**Comment by Tsuchiya2** [comment]
build_flex_messageメソッドとかですね。
コミットメッセージ「LINEコントローラー冗長修正」で.rubocop.ymlと.rubocop_todo.ymlを生成しているようですが、こちらは設定によってはRubocopを通しても意味の無い状態になってしまいます。

一旦、.rubocop.ymlと.rubocop_todo.ymlを削除した状態でRubocopを通して、可能な限り修正しましょう。その後、どうしてもというものを.rubocop.ymlと.rubocop_todo.ymlで記載するようにしてください。

---

そうですね。画像のリサイズだけでなく、ファイル容量が大きいためか、https://osi-b2426bac1a6b.herokuapp.com/public_albums ページをスクロールする際など、重くて操作がすぐに反映されなかったので、ファイルサイズも調整した上でアップロードするようにしましょう。（ブラウザのキャッシュに全ての画像が残っていればスムーズに動きますが、そうでない場合において思いWebアプリといった良くない印象を与えてしまいます）

**Comment by s-chihiro0108** [comment]
MiniMagickを使用してwebpに変換することで画像の軽量化をしたのですがすでにユーザー様に投稿していただいた画像の変更をrakeのタスク実行でおこなように実行したのですが変更できず困っています。すでにある画像を変更しないとサイトの軽量化が計れず意味がないと思うのでヒントをいただけないですか、、

**Comment by Tsuchiya2** [comment]
管理画面やコンソールから差し替える形はいかがでしょうか。
その場合、アップロードされたファイルを自前でサービス上からダウンロードして、それを加工するなりして差し替えてあげるなどの方法ができないか検討してみましょう。

**Comment by s-chihiro0108** [comment]
コンソールから差し替えとはs3から差し替える感じでしょうか、、s3から直接差し替えをこころみたのですがherokuが把握しているURLが前のものを持ってきてしまってエラー出てしまいます。管理者画面とは、railsでactiveadminなどを使用して管理者画面の実装をして、変更を加えるということですか？

**Comment by Tsuchiya2** [comment]
既に登録されているものを破棄して、再アップロードしてあげる感じですね。
もしくはデータを削除してしまうという方法もありかもしれません。

**Comment by s-chihiro0108** [comment]
お返事遅れてすみません。
無事に管理者権限で写真を入れ直し解決しました。アドバイスありがとうございます。
ご指摘頂いた点を全て直しました。（Rubocop、画像圧縮（サイトの重さ）、独自ドメイン取得）
本リリースにつきましては担当CTさんと話し合い今月中にはどうにか終わらせられるように頑張りたいと思います。
